### ISSUE TITLE
怎么验证用户中的鉴权Token

### ISSUE THREAD

**Issue by TTaket** [808-not-found/tik_duck#12]
struct UserRequest {
    1: i64 UserId //用户id
    2: string Token //用户鉴权token
}
用户进行对用户信息请求的时候要求验证token用户鉴权 
问题1： 用户传来的请求token 和什么进行对比判断是否允许或许用户信息
问题2： 失败时返回的验证码规范（仍然使用 401表示鉴权验证失败吗还是自行规定）

**Comment by Bubbleioa** [comment]
使用 jwt https://jwt.io/
就用401
