### ISSUE TITLE
目前测试出现的问题

### ISSUE THREAD

**Issue by TTaket** [808-not-found/tik_duck#54]
- [x] Q1:web很容易因为小错误崩溃关闭
- [x] Q2:web点击关注用户会崩溃

- [ ] #64

- [ ] #63
- [ ] #62

- [ ] #61

- [x] Q7:视频无法播放
- [ ] #60

**Comment by Bubbleioa** [comment]
我看你的 fork 都 This branch is 43 commits behind 808-not-found:master.
你拉取到最新版本试试

**Comment by Bubbleioa** [comment]
可能还需要重建一下docker
把错误信息补充一下。

**Comment by TFMLIN** [comment]
Q2:问题出在RPC部分，现已修复

**Comment by Bubbleioa** [comment]
小错误崩溃是log.fatal的原因，当时开发的时候想着要让错误尽早发现，可以都换了

**Comment by TFMLIN** [comment]
Q9:is_follow在user和useruser里都没能正常处理，疑似pack中的数据库查询语句问题

**Comment by TFMLIN** [comment]
Q2:关注操作和取关操作已修复

**Comment by TFMLIN** [comment]
A7&A8（A代表对Q的回复）：目前我自己这视频播放正常，手机上正常
A3：我这关注操作也是，关注之后取关，仍然占用follow表中的记录，并没有实现软删除操作，而gorm文档中说到delete_at字段有了之后会自动执行软删除，怀疑是配置问题？
A4：刚刚修复了一个粉丝列表的bug

**Comment by TTaket** [comment]
> 我看你的 fork 都 This branch is 43 commits behind 808-not-found:master. 你拉取到最新版本试试

我主要运行的部分都在LJY分支里面 所以会有落后 昨天测试环境是截止今早5点
