### ISSUE TITLE
还有很多功能没有添加/官方文档更新

### ISSUE THREAD

**Issue by TTaket** [808-not-found/tik_duck#65]
飞书： https://bytedance.feishu.cn/docs/doccnKrCsU5Iac6eftnFBdsXTof#
api：   https://www.apifox.cn/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c/api-50707525
![image](https://user-images.githubusercontent.com/107829564/220248037-3591ec51-5b8b-4494-8165-b3ab56fffe6a.png)

**Comment by TTaket** [comment]
但好像不是必须项

**Comment by Bubbleioa** [comment]
不添加
