### ISSUE TITLE
log打印的日志和db里面存储的时间有8个小时的时差 会有影响吗

### ISSUE THREAD

**Issue by TTaket** [808-not-found/tik_duck#72]
![image](https://user-images.githubusercontent.com/107829564/220257762-5ff901be-a99d-451b-8db8-40e5a2be583a.png)
![image](https://user-images.githubusercontent.com/107829564/220257795-5b4c53bd-c04c-4b96-94e2-2d79f4eb4297.png)

**Comment by Bubbleioa** [comment]
时区问题，数据库设置一下UTC+8

**Comment by Bubbleioa** [comment]
fixed in #103
