### ISSUE TITLE
UserInfo问题

### ISSUE THREAD

**Issue by TTaket** [808-not-found/tik_duck#88]
故障信息：
当我用两台手机上app的时候 
a手机给b手机的视频点赞 给b关注
a手机一切正常
数据库一切正常
b手机在‘我’的界面观察不到变化
![img_v2_acbf8974-670c-442e-b289-ba635fb86fag](https://user-images.githubusercontent.com/107829564/220325486-e60599a3-465b-4a16-a41b-3ac32587c5a0.jpg)
![img_v2_cdb1af1e-33b0-44e5-9d64-27306acb3cag](https://user-images.githubusercontent.com/107829564/220325502-fdc4f4c6-2e5b-4c4d-b2ac-72818daa248e.jpg)

**Comment by Bubbleioa** [comment]
你可以重新登陆试试，这个客户端问题还挺多的

**Comment by Bubbleioa** [comment]
这是客户端问题，重启客户端即可看到。
